"""create initial tables

Revision ID: 6a9223df1783
Revises: 
Create Date: 2026-09-30 23:52:53.906996

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6a9223df1783'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('appointments',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='약속 고유 식별자 PK'),
    sa.Column('title', sa.String(length=100), nullable=False, comment='약속 이름 (예: 강남역 맛집 탐방)'),
    sa.Column('target_place_name', sa.String(length=150), nullable=False, comment='도착 장소명'),
    sa.Column('target_address', sa.String(length=255), nullable=True, comment='도착 장소 도로명/지번 주소'),
    sa.Column('target_latitude', sa.Float(), nullable=False, comment='도착지 위도 (Latitude)'),
    sa.Column('target_longitude', sa.Float(), nullable=False, comment='도착지 경도 (Longitude)'),
    sa.Column('meet_at', sa.DateTime(), nullable=False, comment='약속 일시 (UTC)'),
    sa.Column('radar_start_type', sa.String(length=20), nullable=False, comment='레이더 시작 시점 유형'),
    sa.Column('custom_radar_minutes_before', sa.Integer(), nullable=True, comment='CUSTOM 시 약속 N분 전 시작'),
    sa.Column('radar_start_at', sa.DateTime(), nullable=False, comment='계산된 실제 위치 공유(레이더) 시작 시각'),
    sa.Column('penalty_type', sa.String(length=20), nullable=False, comment='벌칙 유형 (PENALTY/FINE)'),
    sa.Column('penalty_content', sa.String(length=150), nullable=True, comment='벌칙 내용 문구 (예: 오늘 커피 쏘기)'),
    sa.Column('fine_per_minute', sa.Integer(), nullable=False, comment='분당 지각 벌금 (원)'),
    sa.Column('invite_code', sa.String(length=12), nullable=False, comment='6자리 초대 난수 코드 (예: ETA99K)'),
    sa.Column('status', sa.String(length=20), nullable=False, comment='약속 상태 (SCHEDULED, RADAR_ACTIVE, COMPLETED, CANCELLED)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_appointments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_appointments_invite_code'), ['invite_code'], unique=True)

    op.create_table('users',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='유저 고유 식별자 PK'),
    sa.Column('guest_uuid', sa.String(length=64), nullable=False, comment='클라이언트 기기 고유 UUID'),
    sa.Column('nickname', sa.String(length=20), nullable=False, comment='사용자 닉네임 (2~10자)'),
    sa.Column('profile_character', sa.String(length=50), nullable=False, comment='선택한 프로필 캐릭터 ID'),
    sa.Column('location_terms_agreed', sa.Boolean(), nullable=False, comment='위치 정보 수집 약관 동의 여부'),
    sa.Column('notification_allowed', sa.Boolean(), nullable=False, comment='FCM 푸시 알림 허용 여부'),
    sa.Column('fcm_token', sa.String(length=255), nullable=True, comment='푸시 알림 전송용 FCM 기기 토큰'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='생성 일시'),
    sa.Column('updated_at', sa.DateTime(), nullable=False, comment='수정 일시'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_guest_uuid'), ['guest_uuid'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_id'), ['id'], unique=False)

    op.create_table('participants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='참가자 고유 식별자 PK'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='유저 식별자 FK'),
    sa.Column('appointment_id', sa.Integer(), nullable=False, comment='약속 식별자 FK'),
    sa.Column('nickname', sa.String(length=20), nullable=False, comment='약속 내 표시 닉네임'),
    sa.Column('is_host', sa.Boolean(), nullable=False, comment='방장 여부'),
    sa.Column('is_ready', sa.Boolean(), nullable=False, comment='준비 완료 여부'),
    sa.Column('join_status', sa.String(length=20), nullable=False, comment='참여 상태 (JOINED, LEFT)'),
    sa.Column('arrival_status', sa.String(length=20), nullable=False, comment='도착 상태 (NOT_ARRIVED, EARLY, ON_TIME, LATE)'),
    sa.Column('arrived_at', sa.DateTime(), nullable=True, comment='실제 도착 인증 시각'),
    sa.Column('final_late_minutes', sa.Integer(), nullable=False, comment='최종 지각 시간 (분)'),
    sa.Column('final_fine_amount', sa.Integer(), nullable=False, comment='최종 정산 지각비 (원)'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_participants_id'), ['id'], unique=False)

    op.create_table('poke_logs',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='찌르기 로그 PK'),
    sa.Column('appointment_id', sa.Integer(), nullable=False, comment='약속 FK'),
    sa.Column('sender_participant_id', sa.Integer(), nullable=False, comment='찌른 사람 FK'),
    sa.Column('target_participant_id', sa.Integer(), nullable=False, comment='찔린 사람 FK'),
    sa.Column('response_action', sa.String(length=30), nullable=True, comment='응답 액션 (NOW_DEPARTING, DISMISSED, NO_RESPONSE)'),
    sa.Column('created_at', sa.DateTime(), nullable=False, comment='찌르기 전송 일시'),
    sa.Column('responded_at', sa.DateTime(), nullable=True, comment='응답 일시'),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['sender_participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_participant_id'], ['participants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('poke_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_poke_logs_id'), ['id'], unique=False)

    op.create_table('warrants',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='영장 고유 식별자 PK'),
    sa.Column('appointment_id', sa.Integer(), nullable=False, comment='대상 약속 FK (1:1)'),
    sa.Column('defendant_participant_id', sa.Integer(), nullable=True, comment='피고인(지각자) 참가자 FK'),
    sa.Column('charge_title', sa.String(length=100), nullable=False, comment='죄명'),
    sa.Column('late_minutes', sa.Integer(), nullable=False, comment='지각 시간 (분)'),
    sa.Column('judgment_text', sa.Text(), nullable=False, comment='판결문 요약 (예: 약속 시간 18분 초과 및 5분간 미출발 검거)'),
    sa.Column('final_penalty', sa.String(length=150), nullable=False, comment='최종 집행 벌칙/지각비 문구'),
    sa.Column('total_fine_amount', sa.Integer(), nullable=False, comment='약속 전체 지각비 총합'),
    sa.Column('share_card_image_url', sa.String(length=500), nullable=True, comment='생성된 영장 카드 이미지 URL'),
    sa.Column('share_link_url', sa.String(length=255), nullable=True, comment='웹 결과 공유 링크 URL'),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['appointment_id'], ['appointments.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['defendant_participant_id'], ['participants.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('appointment_id')
    )
    with op.batch_alter_table('warrants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_warrants_id'), ['id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('warrants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_warrants_id'))

    op.drop_table('warrants')
    with op.batch_alter_table('poke_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_poke_logs_id'))

    op.drop_table('poke_logs')
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_participants_id'))

    op.drop_table('participants')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_id'))
        batch_op.drop_index(batch_op.f('ix_users_guest_uuid'))

    op.drop_table('users')
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_appointments_invite_code'))
        batch_op.drop_index(batch_op.f('ix_appointments_id'))

    op.drop_table('appointments')
    # ### end Alembic commands ###
