"""Add host_id, is_arrived, left_at and unique constraint

Revision ID: 42d5d0cf4ef1
Revises: a752a1988286
Create Date: 2026-10-01 12:23:25.788365

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '42d5d0cf4ef1'
down_revision: Union[str, Sequence[str], None] = 'a752a1988286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('host_id', sa.Integer(), nullable=True, comment='방장 유저 ID FK'))
        batch_op.create_foreign_key('fk_appointments_host_id_users', 'users', ['host_id'], ['id'], ondelete='SET NULL')

    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_arrived', sa.Boolean(), nullable=False, server_default=sa.false(), comment='도착(체크인) 여부'))
        batch_op.add_column(sa.Column('left_at', sa.DateTime(), nullable=True, comment='방 나간(퇴장) 시각'))
        batch_op.create_unique_constraint('uq_participant_appointment_user', ['appointment_id', 'user_id'])

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participants', schema=None) as batch_op:
        batch_op.drop_constraint('uq_participant_appointment_user', type_='unique')
        batch_op.drop_column('left_at')
        batch_op.drop_column('is_arrived')

    with op.batch_alter_table('appointments', schema=None) as batch_op:
        batch_op.drop_constraint('fk_appointments_host_id_users', type_='foreignkey')
        batch_op.drop_column('host_id')

    # ### end Alembic commands ###
